# This file is very important config.yaml
monitor:
  server: 'http://39.99.176.125:28082'
#  server: 'http://localhost:28082'


# You can also add more than one chia crypto by yourself
crypto:
  chia: #name of crypto executable,such as chia.exe,so the value is chia
    enable: true #default false
    executable_path: '/home/wutl/chia-blockchain/venv/bin/' #crypto installed path
    executable_name: 'chia'
    debug_log_path: '/home/wutl/.chia/mainnet/log/debug.log' # log file path, you need open enabled Chia INFO level log
    frequency_sync: 30 #default 300 seconds(5minutes),sync information to monitor server.Note that this period defines how often high priority notifications，will be re-triggered so < 5 min is not recommended
    frequency_check_status: 30 #default 300 seconds(5minutes),check device status,such as farmer status or harvester status.Note < 5 min is not recommended
    farmer_restart: false #default false if true,means when farmer run err or offline,auto restart farmer
    farmer_send_email: true #default false
    harvester_restart: false #default false
    harvester_send_email: true #default false
