# This file is very important config.yaml
monitor:
  server: 'http://39.99.176.125:28082'
#  server: 'http://localhost:28082'


# You can also add more than one chia crypto by yourself
crypto:
  chia: #name of crypto executable,such as chia.exe,so the value is chia
    enable: true #default false
    executable_path: 'C:\Users\wsd\AppData\Local\chia-blockchain\app-1.1.7\resources\app.asar.unpacked\daemon\' #crypto installed path
    executable_name: 'chia.exe'
    debug_log_file: 'C:\Users\wsd\.chia\mainnet\log\debug.log' # log file, you need open enabled Chia INFO level log
    frequency_sync: 300 #default 300 seconds(5minutes),sync information to monitor server.Note that this period defines how often high priority notifications，will be re-triggered so < 5 min is not recommended
    frequency_check_status: 300 #default 300 seconds(5minutes),check device status,such as farmer status or harvester status.Note < 5 min is not recommended
    farmer_restart: false #default false if true,means when farmer run err or offline,auto restart farmer
    farmer_send_email: false #default false
    harvester_restart: false #default false
    harvester_send_email: false #default false

  flax: #name of crypto executable,such as flax.exe,so the value is flax
    enable: true #default false
    executable_path: 'C:\Users\wsd\AppData\Local\flax-blockchain\app-0.1.0\resources\app.asar.unpacked\daemon\'
    executable_name: 'flax.exe'
    debug_log_file: 'C:\Users\wsd\.chia\mainnet\log\debug.log' # log file, you need open enabled Flax INFO level log
    frequency_sync: 600 #default 300 seconds(5minutes),sync information to monitor server
    frequency_check_status: 600 #default 300 seconds(5minutes),check device status,such as farmer status or harvester status
    farmer_restart: false #default false if true,means when farmer run err or offline,auto restart farmer
    farmer_send_email: false #default false
    harvester_restart: false #default false
    harvester_send_email: false #default false
